CREATE ROLE farmer;
GRANT SELECT, INSERT, UPDATE ON TABLE SeedsStorage TO farmer;
GRANT SELECT, INSERT, UPDATE ON TABLE Bed TO farmer;
GRANT SELECT, INSERT, UPDATE ON TABLE GrownVegetablesStorage TO farmer;
GRANT SELECT, INSERT ON TABLE Species TO farmer;
GRANT SELECT ON TABLE Facility TO farmer;
GRANT USAGE ON SCHEMA public TO farmer;
CREATE USER johnlock WITH
	IN ROLE farmer
	ENCRYPTED PASSWORD 'cantunlock';
CREATE USER shaun WITH
	IN ROLE farmer
	ENCRYPTED PASSWORD 'grassinc';
	
CREATE ROLE trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SeedsSellOffer to trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SeedsBuyOffer to trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE VegetableSellOffer to trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE VegetableBuyer to trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SeedBuyer to trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SeedSupplier to trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SeedsToBuy to trader;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SeedsToSell to trader;
GRANT SELECT, INSERT, UPDATE ON TABLE SeedsStorage to trader;
GRANT SELECT, INSERT, UPDATE ON TABLE GrownVegetablesStorage to trader;
GRANT SELECT ON TABLE Facility to trader;
GRANT SELECT ON TABLE Species to trader;
GRANT SELECT ON TABLE Bed to trader;

GRANT USAGE ON SCHEMA public TO trader;
CREATE USER wallwolf WITH
	IN ROLE trader
	ENCRYPTED PASSWORD 'streettrade';
CREATE USER aynrend WITH
	IN ROLE trader
	ENCRYPTED PASSWORD 'giantpass';